apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: lab-tap-sample
spec:
  portal:
    registration:
      type: anonymous
  workshops:
  - name: lab-tap-sample
    capacity: 2
    expires: 60m
    orphaned: 5m
